#### general settings
name: none
model: base
use_tb_logger: false
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: HDRTV1K
    mode: LQGT_base
    dataroot_LQ: ../data/hdrtv1k/training_set/train_sdr_sub_c096_s240
    dataroot_GT: ../data/hdrtv1k/training_set/train_hdr_sub_c096_s240
    use_shuffle: true
    n_workers: 64
    batch_size: 64
    GT_size: 96
    use_flip: false
    use_rot: false
  val:
    name: HDRTV1K
    mode: LQGT_base
    dataroot_LQ: ../data/hdrtv1k/test_set/test_sdr
    dataroot_GT: ../data/hdrtv1k/test_set/test_hdr
    save_img: false

#### network structures
network_G:
  which_model_G: FMNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
  act_type: relu
  FM_kernelSize: 3
  FM_blockNumber: 1
  FM_channelNumber: 16
  FM_kernelNumber: 4

#### path
path:
  root: ./
  # pretrain_model_G: 
  strict_load: false
  # resume_state: 

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4 
  lr_scheme: MultiStepLR # MultiStepLR | CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 100000 # 600000 
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [20000, 40000, 60000, 80000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 2e4

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3